FROM mcr.microsoft.com/dotnet/aspnet:6.0 AS base
WORKDIR /app
EXPOSE 80
EXPOSE 443

FROM mcr.microsoft.com/dotnet/sdk:6.0 AS build
WORKDIR /src
COPY ["APICloud.csproj", "."]
RUN dotnet restore "./APICloud.csproj"
COPY . .
WORKDIR "/src/."
RUN dotnet build "APICloud.csproj" -c Release -o /app/build

FROM build AS publish
RUN dotnet publish "APICloud.csproj" -c Release -o /app/publish

FROM base AS final
WORKDIR /app
